name: CI/CD
on:
  push:
    branches:
      - main

env:
  MY_AWS_REGION: "ap-northeast-1"
  AWS_ROLE_NAME: "GitHubActionsOIDCRole"
  AWS_S3_BUCKET: "www.jikan-kanri-kun.com"

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: "18.17.1"
    - name: Install packages
      run: npm install
    - name: Show coverage
      env:
        REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
      run: npm test -- --bail --maxWorkers=100% --watchAll=false --coverage
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      env:
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_PRODUCTION_API_BASE_URL }}
          # todo とりあえず動くので下記でbuild時に発生するエラーを回避（後々コードを修正）
          CI: false
      run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials with IAM Role
      uses: aws-actions/configure-aws-credentials@main
      with:
        role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{env.AWS_ROLE_NAME}}
        aws-region: ${{env.MY_AWS_REGION}}
    - name: Copy files to S3
      run: aws s3 cp --recursive build s3://${{env.AWS_S3_BUCKET}}/